version: '3.8'

services:
  database:
    container_name: 3-semester-database
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Q23wa!!!32"
      ACCEPT_EULA: "Y"
    networks:
      - product-network

networks: 
    product-network:
        driver: bridge      