version: '3.8'

services:
  backend:
    container_name: 3-semester-backend
    build:
      context: ./Backend/DockerComposeProductApi/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - ./Backend/DockerComposeProductApi/:/app
    ports:
      - "5000:80"  
    depends_on:
      - database
    networks:
      - product-network
  frontend:
    container_name: 3-semester-frontend
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - product-network
  database:
    container_name: 3-semester-database
    image: "mcr.microsoft.com/mssql/server"
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Q23wa!!!32"
      ACCEPT_EULA: "Y"
    networks:
      - product-network

networks: 
    product-network:
        driver: bridge      